[workspace]
members = [
    "ecosystem",
    "ecosystem/Discovery/sentry",
    "ecosystem/Discovery/squire",
    "ecosystem/Discovery/bard"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
